version: '3.1'
services:
  app:
    container_name: handling-request-ms
    image: durpyshark/handling-request-ms
    build: ./
    ports:
      - "8087:8087"
    depends_on:
      - handling_requests_db_container
  handling_requests_db_container:
    image: postgres
    ports:
      - "5439:5439"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=handling_requests_db
    command: -p 5439